---
##########
## Non free plugins
- name: install non free plugins
  unarchive:
    src=files/{{ item }}
    dest={{ redmine_dir }}/plugins
  with_items:
    - EasyGanttFree.zip
    - EasyWBSFree.zip
    - redmine_favorite_projects-2_0_3-light.zip
    - redmine_questions-0_0_7-light.zip
    - redmine_zenedit-0_0_2-light.zip
  ignore_errors: yes

- name: add star icon
  copy: src=star.png dest=/var/lib/redmine/public/images/star.png mode=0644

- name: add css class
  lineinfile:
    dest=/var/lib/redmine/public/stylesheets/application.css
    insertafter=".icon-list"
    line=".icon-star { background-image{{ COLON }} url(../images/star.png); }"

##########
## Other plugins

#- name: install plugins in bitbucket
#  hg:
#    repo=https://bitbucket.org/{{ item.author }}/{{ item.plugin }}
#    dest={{ redmine_dir }}/plugins/{{ item.plugin }}
#  with_items:
#    - { author: "haru_iida"   , plugin: "redmine_theme_changer"}
#    - { author: "haru_iida"   , plugin: "redmine_wiki_extensions"}

- name: install plugins in github
  git:
    repo=https://github.com/{{ item.author }}/{{ item.plugin }}.git
    dest={{ redmine_dir }}/plugins/{{ item.destdir | default(item.plugin) }}
    version={{ item.version | default('master') }}
    force=yes
  with_items:
    # Ticket
    - { author: "akiko-pusu"  , plugin: "redmine_issue_templates"}
    - { author: "hidakatsuya" , plugin: "redmine_default_custom_query"}
    - { author: "Loriowar"    , plugin: "redmine_issues_tree", version: "3.4.x"}
    - { author: "two-pack"    , plugin: "redmine_xlsx_format_issue_exporter"}
    - { author: "matsukei"    , plugin: "redmine_serial_number_field"}
    # CMS
    - { author: "danmunn"     , plugin: "redmine_dmsf"}
    # Wiki
    - { author: "paginagmbh"  , plugin: "redmine_lightbox2"}
    - { author: "peclik"      , plugin: "clipboard_image_paste"}
    - { author: "fcrespel"    , plugin: "redmine_embedded_flash"}
    - { author: "tkusukawa"   , plugin: "redmine_wiki_lists"}
    # usability
    - { author: "ncoders"     , plugin: "redmine_local_avatars"}
    - { author: "bdemirkir"   , plugin: "sidebar_hide"}
    - { author: "akiko-pusu"  , plugin: "redmine_banner"}
    # looks good but not work
    # - { author: "onozaty"     , plugin: "redmine-view-customize", destdir: "view-customize"}
    # - { author: "alexbevi"   , plugin: "redmine_knowledgebase"}

# resolve conflicts of gems
- name: resolve conflicts of gem versions
  replace:
    dest=/var/lib/redmine/plugins/redmine_dmsf/Gemfile
    regexp='rubyzip'.*
    replace=''rubyzip''
    backup=yes

- include: tasks/install.yml
